### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by neoatomic** [DougMac/e2m3u2bouquet-plugin#11]
@DougMac 
The image teams are starting to migrate to Python 3. Are you able to make e2m3u2bouquet Py3 compatible?

Currently the e2m3u2bouquet plugin gives the following error with Py3.  :
"invalid syntax (plugin.py, line 148)"
https://github.com/DougMac/e2m3u2bouquet-plugin/blob/master/plugin.py#L148

**Comment by neoatomic** [comment]
@DougMac @su1s In the repo below are the Py3 commits. Tested, and working. Hopefully you can merge those so future development is in sync. :
https://github.com/oe-mirrors/e2m3u2bouquet-plugin

**Comment by DougMac** [comment]
Thanks for letting me know. I'll test the changes on my python 2 box and get the master branches up to date.
